apiVersion: v1
kind: Service
metadata:
  name: hsl-map-server
spec:
  selector:
    app: hsl-map-server
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: graphiql
spec:
  selector:
    app: graphiql
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: photon-pelias-adapter
spec:
  selector:
    app: photon-pelias-adapter
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: swu-ladesaeulen
spec:
  selector:
    app: swu-ladesaeulen
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui
spec:
  selector:
    app: digitransit-ui
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-container
spec:
  selector:
    app: opentripplanner-data-container
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: opentripplanner
spec:
  selector:
    app: opentripplanner
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-container
  labels:
    app: opentripplanner-data-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentripplanner-data-container
  template:
    metadata:
      labels:
        app: opentripplanner-data-container
    spec:
      containers:
      - name: opentripplanner-data-container
        image: verschwoerhaus/opentripplanner-data-container-vsh:2021-04-15-latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner
  labels:
    app: opentripplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentripplanner
  template:
    metadata:
      labels:
        app: opentripplanner
    spec:
      containers:
      - name: opentripplanner
        image: mfdz/opentripplanner:fe76ec41335f86acc5ea755a15cb4c3d4ea846d7
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
        - name: ROUTER_NAME
          value: vsh
        - name: ROUTER_DATA_CONTAINER_URL
          value: http://opentripplanner-data-container
        - name: JAVA_OPTS
          value: "-Xms10G -Xmx10G"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui
  labels:
    app: digitransit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digitransit-ui
  template:
    metadata:
      labels:
        app: digitransit-ui
    spec:
      containers:
      - name: digitransit-ui
        image: verschwoerhaus/digitransit-ui:1c79174
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG
          value: vsh
        - name: OTP_URL
          value: "https://api.digitransit.im.verschwoerhaus.de/routing/v1/routers/vsh/"
        - name: GEOCODING_BASE_URL
          value: "https://api.digitransit.im.verschwoerhaus.de/geocoding/v1"
        - name: MAP_URL
          value: "https://osm-demo-{s}.wheregroup.com/tiles/1.0.0/osm/webmercator/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-map-server
  labels:
    app: hsl-map-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsl-map-server
  template:
    metadata:
      labels:
        app: hsl-map-server
    spec:
      containers:
      - name: hsl-map-server
        image: verschwoerhaus/hsl-map-server:deb10be
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
        - name: OTP_URL
          value: opentripplanner:8080/otp/routers/vsh/index/graphql
        - name: PARK_API_URL
          value: https://api.parkendd.de/Ulm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphiql
  labels:
    app: graphiql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphiql
  template:
    metadata:
      labels:
        app: graphiql
    spec:
      containers:
      - name: graphiql
        image: verschwoerhaus/graphiql:2019-10-30
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
        - name: URL_PREFIX
          value: https://api.digitransit.im.verschwoerhaus.de
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photon-pelias-adapter
  labels:
    app: photon-pelias-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photon-pelias-adapter
  template:
    metadata:
      labels:
        app: photon-pelias-adapter
    spec:
      containers:
      - name: photon-pelias-adapter
        image: stadtulm/photon-pelias-adapter:47c824d
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
        - name: PHOTON_URL
          value: https://photon.stadtnavi.eu/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swu-ladesaeulen
  labels:
    app: swu-ladesaeulen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swu-ladesaeulen
  template:
    metadata:
      labels:
        app: swu-ladesaeulen
    spec:
      containers:
      - name: swu-ladesaeulen
        image: stadtulm/swu-ladesaeulen:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080

