---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitransit
spec:
  tls:
    - hosts:
      - digitransit.im.verschwoerhaus.de
      - api.digitransit.im.verschwoerhaus.de
      secretName: tls-digitransitimverschwoerhausde
  rules:
  - host: digitransit.im.verschwoerhaus.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: digitransit-ui
            port: 
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitransit-api
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-max-age: "7200"
spec:
  tls:
    - hosts:
      - digitransit.im.verschwoerhaus.de
      - api.digitransit.im.verschwoerhaus.de
      secretName: tls-digitransitimverschwoerhausde
  rules:
  - host: api.digitransit.im.verschwoerhaus.de
    http:
      paths:
      - path: /map/v1
        pathType: Prefix
        backend:
          service:
            name: hsl-map-server
            port: 
              number: 8080
      - path: /graphiql
        pathType: Prefix
        backend:
          service:
            name: graphiql
            port: 
              number: 8080
      - path: /swu-ladesaeulen/v1/
        pathType: Prefix
        backend:
          service:
            name: swu-ladesaeulen
            port: 
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitransit-api-geocoding
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /v1/$2
spec:
  tls:
    - hosts:
      - digitransit.im.verschwoerhaus.de
      - api.digitransit.im.verschwoerhaus.de
      secretName: tls-digitransitimverschwoerhausde
  rules:
  - host: api.digitransit.im.verschwoerhaus.de
    http:
      paths:
      - path: /geocoding/v1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: photon-pelias-adapter
            port: 
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitransit-api-routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /otp/$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,OTPTimeout,id"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-max-age: "7200"
spec:
  tls:
    - hosts:
      - digitransit.im.verschwoerhaus.de
      - api.digitransit.im.verschwoerhaus.de
      secretName: tls-digitransitimverschwoerhausde
  rules:
  - host: api.digitransit.im.verschwoerhaus.de
    http:
      paths:
      - path: /routing/v1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: opentripplanner
            port: 
              number: 8080
